# Generated by Django 2.1.8 on 2019-07-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='Nicknaem',
            new_name='picknaem',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='Picture',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='Username',
            new_name='username',
        ),
    ]
