# Generated by Django 2.2.1 on 2019-07-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20190722_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='good_date',
            new_name='goods_date',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='good_description',
            new_name='goods_description',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='good_number',
            new_name='goods_number',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='good_safeDate',
            new_name='goods_safeDate',
        ),
    ]
